name: map_utils
repository: https://github.com/ubxty/map_utils

packages:
  - packages/*

command:
  bootstrap:
    usePubspecOverrides: true

  version:
    branch: main
    linkToCommits: true

scripts:
  analyze:
    run: dart analyze --fatal-infos
    exec:
      concurrency: 3
    packageFilters:
      dirExists: lib

  test:
    run: flutter test
    exec:
      concurrency: 1
      failFast: true
    packageFilters:
      dirExists: test

  format:
    run: dart format .
    exec:
      concurrency: 3
